name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dep
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish
        run: pnpm pbs
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

