name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Set node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https:registry.npmjs.org/
          cache: pnpm

      - name: Publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: pnpm pbs
