name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https:registry.npmjs.org/
      
      - name: Publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish
